#!/usr/bin/env bash
# script to transfer a file from clinet to server using scp

if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# arguments
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "${username}@${server_ip}":"$file_path"
