#!/usr/bin/env bash

# update the packages
sudo apt-get update -y

# install inginx
sudo apt-get install nginx -y

# start nginx
sudo service nginx start

# allowing firewall
sudo ufw allow 'Nginx HTTP'

# give ownership permissions
sudo chown -R $USER:$USER /var/www/html

sudo chmod -R 755 /var/www

# creating index
echo 'Hello World!' > /var/www/html/index.html

# restart nginx
sudo service nginx restart
