#!/usr/bin/env bash
# custom 404 page
if ! command -v nginx &> /dev/null
then
    sudo apt -y update
    sudo apt install nginx -y
    sudo ufw allow 'Nginx HTTP'
    echo 'Hello World!' > /var/www/html/index.nginx-debian.html
    replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
    sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default
fi

# 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
