#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and hi in the ninth iteration
count=0
while [ $count -le 9 ]; do
    if [ $count -eq 8 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((count++))
done
