#!/usr/bin/env bash
#loop from 1 to 10 and display strings
count=0
while [ $count -lt 10 ]; do
    if [ $count -eq 3 ]; then
        echo "bad luck"
        ((count++))
    elif [ $count -eq 7 ]; then
        echo "good luck"
        ((count++))
    else
        echo "Best School"
        ((count++))
    fi
done
