#!/usr/bin/env bash
#count to 30 while inserting strings
count=1
while [ "$count" -le 20 ]; do
    case "$count" in
    4)
        echo "$count"
        echo "bad luck from China"
        ;;
    9)
        echo "$count"
        echo "bad luck from Japan"
        ;;
    17)
        echo "$count"
        echo "bad luck from Italy"
        ;;
    *)
        echo "$count"
        ;;
    esac
    ((count++))
done
